# To execute this docker compose yml file use `docker compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3.yml down`
services:
  chrome:
    image: selenium/node-chrome:4.38.0-20251101
    platform: linux/amd64
    shm_size: 2gb
    deploy:
      mode: replicated
      replicas: 9
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_VNC_NO_PASSWORD=true
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24

#  edge:
#    image: selenium/node-edge:4.38.0-20251101
#    platform: linux/amd64
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub

#  firefox:
#    image: selenium/node-firefox:4.38.0-20251101
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub

  selenium-hub:
    image: selenium/hub:4.38.0-20251101
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"